TARGET_BOARD_PLATFORM := rk3288
TARGET_BOOTLOADER_BOARD_NAME := rk3288_m2
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_VARIANT := cortex-a15

# CORRECT: Use $(LOCAL_PATH)
TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/prebuilt/zImage
TARGET_DTB := $(LOCAL_PATH)/prebuilt/dt.img

BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_KERNEL_IMAGE_NAME := zImage
TARGET_RECOVERY_FSTAB := device/rockchip/rk3288_m2/recovery.fstab
TARGET_SCREEN_DENSITY := 160
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# Fix bootanimation
TARGET_SCREEN_WIDTH := 1920
TARGET_SCREEN_HEIGHT := 1080
