# BoardConfig.mk

TARGET_BOARD_PLATFORM := rk3288
TARGET_BOOTLOADER_BOARD_NAME := rk3288_m2

# Architecture (RK3288 is 32-bit ARMv7)
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a17

# Kernel
TARGET_KERNEL_SOURCE := kernel/rockchip/linux-4.4
TARGET_KERNEL_CONFIG := rk3288_m2_defconfig
TARGET_PREBUILT_KERNEL := device/rockchip/rk3288_m2/prebuilt/zImage
TARGET_DTB := device/rockchip/rk3288_m2/prebuilt/dt.img

# Partitions (from your parameter.txt)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432     # 32MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824  # 1GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648 # 2GB
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456   # 256MB
BOARD_FLASH_BLOCK_SIZE := 4096

# Recovery
TARGET_RECOVERY_FSTAB := device/rockchip/rk3288_m2/recovery.fstab

# Display
TARGET_SCREEN_DENSITY := 160
BOARD_HAS_NO_SELECT_BUTTON := true

# Vendor
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
